<a href="https://colab.research.google.com/github/Brenda01234/Generative-AI/blob/main/Numpy%20work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
## Array and Lists

In [3]:
a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
