<a href="https://colab.research.google.com/github/Brenda01234/Generative-AI/blob/main/Numpy%20work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
## Array and Lists

In [3]:
a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


**Type Casting**

In [8]:
 arr=np.array([1,2,3.0],dtype="int64")
 print(arr)

 b=np.array([1,2,3.0],dtype="float64")
 print(b)

 new_b=b.astype("int64")
 print(new_b)

[1 2 3]
[1. 2. 3.]
[1 2 3]


In [15]:
# Reshaping Arrays

d=np.array([[3,5],[4,6]])
print(d)

d.ndim #check dimension
d.shape #check shape
d.dtype
d.reshape(1,4)



# Flatten - -> convert array into 1D array without returning a view

d.flatten()

[[3 5]
 [4 6]]


array([3, 5, 4, 6])

In [ ]:
# Ravel - -> convert array into 1D array and returns a view
d.ravel()

**Arthimetic Operation**

In [ ]:
n=np.array([1,2,3,4])
m=np.array([5,6,7,8])

print(n+m)
print(n-m)
print(n*m)
print(n/m)